baseURL:  "https://pritpalcodes.github.io"
languageCode: 'en-us'
title: 'Pritpal Singh'
theme: "PaperMod"

paginate: 5

# enableInlineShortcodes: true
# enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false
# enableEmoji: true
# pygmentsUseClasses: true

languages:
  en:
    languageName: "English"
    weight: 1
    # taxonomies:
    #   category: categories
    #   tag: tags
    #   series: series
    menu:
      main:
        # -name: Home
        #   url: "https://www.amazon.in/"
        #   weight: 10
        - name: About Me
          url: about_me/
          weight: 30
        - name: Experience
          url: experience/
          weight: 30
        - name: Projects
          url: /projects
          weight: 30
        - name: Blogs
          url: /blogs
          weight: 30
        - name: Tags
          url: /tags
          weight: 30
        - name: Resume
          url: /resume/
          weight: 30
        
        # - name: Posts
        #   url: /posts
        #   weight: 40
       


params:
  # ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowReadingTime: true
  # ShowToc: true
  ShowWordCount: true
  # ShowShareButtons: true
  ShowPostNavLinks: true
  # ShowRssButtonInSectionTermList: true
  # ShowRssButtonInSectionList: true
  # ShowRssButtonInHomePage: true
  # ShowBrandIcon: true
  # ShowEditPageButtons: true
  # ShowComments: true
  # ShowLastmod: true
  # ShowRelatedPosts: true
  # ShowSearch: true
  ShowTags: true
  # ShowTaxonomyCloud: true
  ShowPagination: true
  # ShowReadingTime: true
  # ShowShareButtons: true


  # mainSections:
  #   - Projects
  # #   - About Me

  
  homeInfoParams:
    title: " Hi, I'm PritpalðŸ‘‹"
    content: "  ##  A Computer Science Student & a ML Enthusiast!
    

    â€¢ Currently in 4th year, pursuing a B.Tech in Information Technology from JIIT Noida ðŸŽ“ 

    
    â€¢ SemiFinalist at `Adobe GenSolve AI Challenge 2024` ðŸ†


    â€¢ I can type 150 words a minute, still my girlfriend complains that I don't reply her fast enough ðŸ˜…


    > `Actively seeking opportunities in Prodcut Management, Data Science & ML`
    "

  socialIcons:
    - name: github
      title: See my latest projects on github
      url: "https://github.com/pritpalcodes"

    - name: linkedin
      title: See a more professional photo of me @ linkedin
      url: "https://www.linkedin.com/in/oye-pritpal/"
    
    - name: discord
      title: Even I am figuring out how to use Discord
      url: "https://discord.com/"
    
    - name: X
      title: Say hi on X/Twitter
      url: https://twitter.com/oye_pritpal
  
  # menu:
  #   main:
  #     - identifier: resume
  #       name: Resume
  #       url: /PritpalSingh-DataScience.pdf
  #       weight: 50
  #       params:
  #         icon: file-pdf

